/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.taul;

import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author MADA
 */
public class tiketTaul extends javax.swing.JFrame {
    int vip,ekonomi,harga,beli,total,bayar,kembali;
    /**
     * Creates new form tiketTaul
     */
    public tiketTaul() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupkereta = new javax.swing.ButtonGroup();
        grupKAPAL = new javax.swing.ButtonGroup();
        grupPESAWAT = new javax.swing.ButtonGroup();
        grupBIOSKOP = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        tombolKERETA = new javax.swing.JLabel();
        tombolKAPAL = new javax.swing.JLabel();
        tombolPESAWAT = new javax.swing.JLabel();
        tombolBIOSKOP = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        namaPEMESAN = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        panelUTAMA = new javax.swing.JPanel();
        panelMasuk = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namaMasuk = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        panelPilih = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        panelKereta = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        pilihKereta = new javax.swing.JComboBox<>();
        keretaEKONOMI = new javax.swing.JRadioButton();
        keretaVIP = new javax.swing.JRadioButton();
        keretaHarga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        keretaNOMOR = new javax.swing.JTextField();
        keretaNAMA = new javax.swing.JLabel();
        keretaJUMLAH = new javax.swing.JTextField();
        keretaTOTAL = new javax.swing.JLabel();
        keretaBAYAR = new javax.swing.JTextField();
        keretaKEMBALIAN = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        keretaRESI = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel50 = new javax.swing.JLabel();
        panelKapal = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        kapalHARGA = new javax.swing.JLabel();
        kapalEKONOMI = new javax.swing.JRadioButton();
        kapalVIP = new javax.swing.JRadioButton();
        pilihKAPAL = new javax.swing.JComboBox<>();
        jLabel20 = new javax.swing.JLabel();
        kapalNOMOR = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        kapalNAMA = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        kapalJUMLAH = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        kapalTOTAL = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        kapalBAYAR = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        kapalKEMBALIAN = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        kapalRESI = new javax.swing.JTextArea();
        jLabel49 = new javax.swing.JLabel();
        panelPesawat = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        pilihPesawat = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        pesawatEKONOMI = new javax.swing.JRadioButton();
        pesawatVIP = new javax.swing.JRadioButton();
        pesawatHARGA = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pesawatRESI = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        pesawatKEMBALIAN = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pesawatBAYAR = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        pesawatTOTAL = new javax.swing.JLabel();
        pesawatJUMLAH = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        pesawatNAMA = new javax.swing.JLabel();
        pesawatNOMOR = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        panelBIOSKOP = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        pilihBioskop = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        bioskopEKONOMI = new javax.swing.JRadioButton();
        bioskopVIP = new javax.swing.JRadioButton();
        bioskopHARGA = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        bioskopNOMOR = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        bioskopNAMA = new javax.swing.JLabel();
        bioskopJUMLAH = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        bioskopTOTAL = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        bioskopBAYAR = new javax.swing.JTextField();
        bioskopKEMBALIAN = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        bioskopRESI = new javax.swing.JTextArea();
        jLabel47 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 119, 1));

        tombolKERETA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tombolKERETA.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/kereta taul.png"))); // NOI18N
        tombolKERETA.setText("KERETA");
        tombolKERETA.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolKERETA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolKERETAMouseClicked(evt);
            }
        });

        tombolKAPAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tombolKAPAL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/kapal taul.png"))); // NOI18N
        tombolKAPAL.setText("KAPAL");
        tombolKAPAL.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolKAPAL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolKAPALMouseClicked(evt);
            }
        });

        tombolPESAWAT.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tombolPESAWAT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/pesawat taul.png"))); // NOI18N
        tombolPESAWAT.setText("PESAWAT");
        tombolPESAWAT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolPESAWAT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolPESAWATMouseClicked(evt);
            }
        });

        tombolBIOSKOP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        tombolBIOSKOP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/tiket taul.png"))); // NOI18N
        tombolBIOSKOP.setText("BIOSKOP");
        tombolBIOSKOP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tombolBIOSKOP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tombolBIOSKOPMouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("MENU");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Yu Gothic UI Semibold", 2, 12)); // NOI18N
        jLabel45.setText("BY : URAY ITAUL RIZKY");

        jLabel51.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/pngfind.com-exit-sign-png-2066595.png"))); // NOI18N
        jLabel51.setText("EXIT");
        jLabel51.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel51.setDisabledIcon(null);
        jLabel51.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel51MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tombolPESAWAT)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(31, 31, 31)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tombolBIOSKOP)
                                        .addComponent(tombolKAPAL)
                                        .addComponent(tombolKERETA)
                                        .addComponent(jLabel51)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel45))))
                        .addGap(0, 15, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tombolKERETA)
                .addGap(29, 29, 29)
                .addComponent(tombolKAPAL)
                .addGap(27, 27, 27)
                .addComponent(tombolPESAWAT)
                .addGap(29, 29, 29)
                .addComponent(tombolBIOSKOP)
                .addGap(18, 18, 18)
                .addComponent(jLabel51)
                .addGap(52, 52, 52)
                .addComponent(jLabel45)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 440));

        jPanel2.setBackground(new java.awt.Color(198, 21, 29));

        namaPEMESAN.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        namaPEMESAN.setText("name");

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/bitcoin_PNG48.png"))); // NOI18N

        jLabel52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/64px-Logo-tiket-com.png"))); // NOI18N

        jLabel53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/kisspng-logo-brand-product-design-font-startup-indonesia-ilmu-com-tempat-menambah-me-5ba3a3a1e882b2.0082474115374509139524.png"))); // NOI18N

        jLabel54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/kisspng-mister-aladin-hotel-travel-website-discounts-and-a-5af87d82e84553.9629143315262344989514.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(namaPEMESAN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 288, Short.MAX_VALUE)
                .addComponent(jLabel54)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel52, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel53, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel46)
                .addGap(46, 46, 46))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(namaPEMESAN))
                        .addComponent(jLabel46)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel53)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel52)))
                    .addComponent(jLabel54))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 570, 60));

        panelUTAMA.setBackground(new java.awt.Color(162, 37, 31));
        panelUTAMA.setLayout(new java.awt.CardLayout());

        panelMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panelMasuk.setOpaque(false);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("SILAKAN MASUKAN NAMA ANDA");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("NAMA");

        namaMasuk.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        namaMasuk.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        namaMasuk.setOpaque(false);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("MASUK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMasukLayout = new javax.swing.GroupLayout(panelMasuk);
        panelMasuk.setLayout(panelMasukLayout);
        panelMasukLayout.setHorizontalGroup(
            panelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasukLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel2)
                .addGap(160, 160, 160)
                .addComponent(namaMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMasukLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMasukLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMasukLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(222, 222, 222))))
        );
        panelMasukLayout.setVerticalGroup(
            panelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMasukLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(panelMasukLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namaMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(55, 55, 55)
                .addComponent(jButton1)
                .addContainerGap(136, Short.MAX_VALUE))
        );

        panelUTAMA.add(panelMasuk, "card2");

        panelPilih.setOpaque(false);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/kisspng-art-film-logo-cinema-clip-art-movie-logo-cliparts-5ab587fb2edc64.812960291521846267192.png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/3-2-ship-png-hd.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/2cd43b_91c3a802bf8a4322bb440eb9dffef340_mv2.png"))); // NOI18N

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/29545-7-train-transparent-background.png"))); // NOI18N

        javax.swing.GroupLayout panelPilihLayout = new javax.swing.GroupLayout(panelPilih);
        panelPilih.setLayout(panelPilihLayout);
        panelPilihLayout.setHorizontalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilihLayout.createSequentialGroup()
                .addContainerGap(773, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(112, 112, 112))
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel44))
                .addGap(104, 104, 104))
        );
        panelPilihLayout.setVerticalGroup(
            panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel4)
                .addGap(29, 29, 29)
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(panelPilihLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPilihLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPilihLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel44)
                        .addGap(62, 62, 62))))
        );

        panelUTAMA.add(panelPilih, "card4");

        panelKereta.setOpaque(false);
        panelKereta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("JURUSAN");
        panelKereta.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, -1, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("KELAS");
        panelKereta.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 79, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel10.setText("HARGA");
        panelKereta.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, -1, -1));

        pilihKereta.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pilihKereta.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JURUSAN", "KUBU RAYA", "SAMBAS", "SINGKAWANG", "KAPUAS HULU" }));
        pilihKereta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKeretaActionPerformed(evt);
            }
        });
        panelKereta.add(pilihKereta, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 29, 130, -1));

        grupkereta.add(keretaEKONOMI);
        keretaEKONOMI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaEKONOMI.setText("EKONOMI");
        keretaEKONOMI.setOpaque(false);
        keretaEKONOMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaEKONOMIActionPerformed(evt);
            }
        });
        panelKereta.add(keretaEKONOMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 75, -1, -1));

        grupkereta.add(keretaVIP);
        keretaVIP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaVIP.setText("VIP");
        keretaVIP.setOpaque(false);
        keretaVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keretaVIPActionPerformed(evt);
            }
        });
        panelKereta.add(keretaVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 75, -1, -1));

        keretaHarga.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaHarga.setText("jLabel11");
        panelKereta.add(keretaHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel12.setText("NOMOR PEMESAN");
        panelKereta.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 32, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel13.setText("NAMA PEMESAN");
        panelKereta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 79, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel15.setText("TOTAL");
        panelKereta.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 171, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel16.setText("UANG BAYAR");
        panelKereta.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 215, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel17.setText("KEMBALIAN");
        panelKereta.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 250, -1, -1));

        keretaNOMOR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaNOMOR.setToolTipText("");
        keretaNOMOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keretaNOMORKeyTyped(evt);
            }
        });
        panelKereta.add(keretaNOMOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 29, 111, -1));

        keretaNAMA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaNAMA.setText("jLabel18");
        panelKereta.add(keretaNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 79, -1, -1));

        keretaJUMLAH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaJUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keretaJUMLAHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keretaJUMLAHKeyTyped(evt);
            }
        });
        panelKereta.add(keretaJUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 126, 111, -1));

        keretaTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaTOTAL.setText("jLabel19");
        panelKereta.add(keretaTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 171, -1, -1));

        keretaBAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                keretaBAYARKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                keretaBAYARKeyTyped(evt);
            }
        });
        panelKereta.add(keretaBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 212, 111, -1));

        keretaKEMBALIAN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        keretaKEMBALIAN.setText("jLabel20");
        panelKereta.add(keretaKEMBALIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 250, -1, -1));

        keretaRESI.setEditable(false);
        keretaRESI.setColumns(20);
        keretaRESI.setRows(5);
        jScrollPane1.setViewportView(keretaRESI);

        panelKereta.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 157, 271, 212));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton2.setText("CETAK RESI");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        panelKereta.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 282, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton3.setText("NEXT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        panelKereta.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 282, -1, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/pngfind.com-train-png-1823306.png"))); // NOI18N
        jLabel50.setText("jLabel50");
        panelKereta.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        panelKapal.setOpaque(false);
        panelKapal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel11.setText("JURUSAN");
        panelKapal.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel18.setText("KELAS");
        panelKapal.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 79, -1, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel19.setText("HARGA");
        panelKapal.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, -1, -1));

        kapalHARGA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalHARGA.setText("jLabel11");
        panelKapal.add(kapalHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, -1, -1));

        grupKAPAL.add(kapalEKONOMI);
        kapalEKONOMI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalEKONOMI.setText("EKONOMI");
        kapalEKONOMI.setOpaque(false);
        kapalEKONOMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapalEKONOMIActionPerformed(evt);
            }
        });
        panelKapal.add(kapalEKONOMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 75, -1, -1));

        grupKAPAL.add(kapalVIP);
        kapalVIP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalVIP.setText("VIP");
        kapalVIP.setOpaque(false);
        kapalVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kapalVIPActionPerformed(evt);
            }
        });
        panelKapal.add(kapalVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 75, -1, -1));

        pilihKAPAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pilihKAPAL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JURUSAN", "TANJUNG PERIOK", "SEMARANG", "TANJUNG PINANG", "SURABAYA" }));
        pilihKAPAL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihKAPALActionPerformed(evt);
            }
        });
        panelKapal.add(pilihKAPAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 29, 130, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel20.setText("NOMOR PEMESAN");
        panelKapal.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 32, -1, -1));

        kapalNOMOR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalNOMOR.setToolTipText("");
        kapalNOMOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kapalNOMORKeyTyped(evt);
            }
        });
        panelKapal.add(kapalNOMOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 29, 111, -1));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel21.setText("NAMA PEMESAN");
        panelKapal.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 79, -1, -1));

        kapalNAMA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalNAMA.setText("jLabel18");
        panelKapal.add(kapalNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 79, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel22.setText("JUMLAH TIKET");
        panelKapal.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 129, -1, -1));

        kapalJUMLAH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalJUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kapalJUMLAHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kapalJUMLAHKeyTyped(evt);
            }
        });
        panelKapal.add(kapalJUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 126, 111, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel23.setText("TOTAL");
        panelKapal.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 171, -1, -1));

        kapalTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalTOTAL.setText("jLabel19");
        panelKapal.add(kapalTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 171, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel24.setText("UANG BAYAR");
        panelKapal.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 215, -1, -1));

        kapalBAYAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalBAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                kapalBAYARKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                kapalBAYARKeyTyped(evt);
            }
        });
        panelKapal.add(kapalBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 212, 111, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel25.setText("KEMBALIAN");
        panelKapal.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 250, -1, -1));

        kapalKEMBALIAN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        kapalKEMBALIAN.setText("jLabel20");
        panelKapal.add(kapalKEMBALIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 250, -1, -1));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton4.setText("CETAK RESI");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        panelKapal.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 282, -1, -1));

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton5.setText("NEXT");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        panelKapal.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 282, -1, -1));

        kapalRESI.setEditable(false);
        kapalRESI.setColumns(20);
        kapalRESI.setRows(5);
        jScrollPane2.setViewportView(kapalRESI);

        panelKapal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 157, 271, 212));

        jLabel49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/ship.jpg.png"))); // NOI18N
        jLabel49.setText("jLabel49");
        panelKapal.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        panelKereta.add(panelKapal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        panelUTAMA.add(panelKereta, "card3");

        panelPesawat.setOpaque(false);
        panelPesawat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel26.setText("JURUSAN");
        panelPesawat.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, -1, -1));

        pilihPesawat.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pilihPesawat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JURUSAN", "JAKARTA", "BANDUNG", "MEDAN", "BALIKPAPAN" }));
        pilihPesawat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihPesawatActionPerformed(evt);
            }
        });
        panelPesawat.add(pilihPesawat, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 29, 130, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel27.setText("KELAS");
        panelPesawat.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 79, -1, -1));

        grupPESAWAT.add(pesawatEKONOMI);
        pesawatEKONOMI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatEKONOMI.setText("EKONOMI");
        pesawatEKONOMI.setOpaque(false);
        pesawatEKONOMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesawatEKONOMIActionPerformed(evt);
            }
        });
        panelPesawat.add(pesawatEKONOMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 75, -1, -1));

        grupPESAWAT.add(pesawatVIP);
        pesawatVIP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatVIP.setText("VIP");
        pesawatVIP.setOpaque(false);
        pesawatVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesawatVIPActionPerformed(evt);
            }
        });
        panelPesawat.add(pesawatVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 75, -1, -1));

        pesawatHARGA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatHARGA.setText("jLabel11");
        panelPesawat.add(pesawatHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel28.setText("HARGA");
        panelPesawat.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, -1, -1));

        pesawatRESI.setEditable(false);
        pesawatRESI.setColumns(20);
        pesawatRESI.setRows(5);
        jScrollPane3.setViewportView(pesawatRESI);

        panelPesawat.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 157, 271, 212));

        jButton6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton6.setText("CETAK RESI");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelPesawat.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 282, -1, -1));

        jButton7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton7.setText("NEXT");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        panelPesawat.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 282, -1, -1));

        pesawatKEMBALIAN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatKEMBALIAN.setText("jLabel20");
        panelPesawat.add(pesawatKEMBALIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 250, -1, -1));

        jLabel29.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel29.setText("KEMBALIAN");
        panelPesawat.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 250, -1, -1));

        pesawatBAYAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatBAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesawatBAYARKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesawatBAYARKeyTyped(evt);
            }
        });
        panelPesawat.add(pesawatBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 212, 111, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel30.setText("UANG BAYAR");
        panelPesawat.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 215, -1, -1));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel31.setText("TOTAL");
        panelPesawat.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 171, -1, -1));

        pesawatTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatTOTAL.setText("jLabel19");
        panelPesawat.add(pesawatTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 171, -1, -1));

        pesawatJUMLAH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatJUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pesawatJUMLAHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesawatJUMLAHKeyTyped(evt);
            }
        });
        panelPesawat.add(pesawatJUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 126, 111, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel32.setText("JUMLAH TIKET");
        panelPesawat.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 129, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel33.setText("NAMA PEMESAN");
        panelPesawat.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 79, -1, -1));

        pesawatNAMA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatNAMA.setText("jLabel18");
        panelPesawat.add(pesawatNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 79, -1, -1));

        pesawatNOMOR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pesawatNOMOR.setToolTipText("");
        pesawatNOMOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                pesawatNOMORKeyTyped(evt);
            }
        });
        panelPesawat.add(pesawatNOMOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 29, 111, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel34.setText("NOMOR PEMESAN");
        panelPesawat.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 32, -1, -1));

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/plane.png"))); // NOI18N
        jLabel48.setText("jLabel48");
        panelPesawat.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        panelUTAMA.add(panelPesawat, "card6");

        panelBIOSKOP.setOpaque(false);
        panelBIOSKOP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel35.setText("JURUSAN");
        panelBIOSKOP.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 32, -1, -1));

        pilihBioskop.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        pilihBioskop.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PILIH JURUSAN", "ANT-MAN", "IRON MAN", "BATMAN", "SUPERMAN" }));
        pilihBioskop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihBioskopActionPerformed(evt);
            }
        });
        panelBIOSKOP.add(pilihBioskop, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 29, 130, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel36.setText("KELAS");
        panelBIOSKOP.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 79, -1, -1));

        grupPESAWAT.add(bioskopEKONOMI);
        bioskopEKONOMI.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopEKONOMI.setText("EKONOMI");
        bioskopEKONOMI.setOpaque(false);
        bioskopEKONOMI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskopEKONOMIActionPerformed(evt);
            }
        });
        panelBIOSKOP.add(bioskopEKONOMI, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 75, -1, -1));

        grupPESAWAT.add(bioskopVIP);
        bioskopVIP.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopVIP.setText("VIP");
        bioskopVIP.setOpaque(false);
        bioskopVIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bioskopVIPActionPerformed(evt);
            }
        });
        panelBIOSKOP.add(bioskopVIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 75, -1, -1));

        bioskopHARGA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopHARGA.setText("jLabel11");
        panelBIOSKOP.add(bioskopHARGA, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 129, -1, -1));

        jLabel37.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel37.setText("HARGA");
        panelBIOSKOP.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 129, -1, -1));

        bioskopNOMOR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopNOMOR.setToolTipText("");
        bioskopNOMOR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bioskopNOMORKeyTyped(evt);
            }
        });
        panelBIOSKOP.add(bioskopNOMOR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 29, 111, -1));

        jLabel38.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel38.setText("NOMOR PEMESAN");
        panelBIOSKOP.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 32, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel39.setText("NAMA PEMESAN");
        panelBIOSKOP.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 79, -1, -1));

        bioskopNAMA.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopNAMA.setText("jLabel18");
        panelBIOSKOP.add(bioskopNAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 79, -1, -1));

        bioskopJUMLAH.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopJUMLAH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bioskopJUMLAHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bioskopJUMLAHKeyTyped(evt);
            }
        });
        panelBIOSKOP.add(bioskopJUMLAH, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 126, 111, -1));

        jLabel40.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel40.setText("JUMLAH TIKET");
        panelBIOSKOP.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 129, -1, -1));

        jLabel41.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel41.setText("TOTAL");
        panelBIOSKOP.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 171, -1, -1));

        bioskopTOTAL.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopTOTAL.setText("jLabel19");
        panelBIOSKOP.add(bioskopTOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 171, -1, -1));

        jLabel42.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel42.setText("UANG BAYAR");
        panelBIOSKOP.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 215, -1, -1));

        bioskopBAYAR.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopBAYAR.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                bioskopBAYARKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bioskopBAYARKeyTyped(evt);
            }
        });
        panelBIOSKOP.add(bioskopBAYAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 212, 111, -1));

        bioskopKEMBALIAN.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bioskopKEMBALIAN.setText("jLabel20");
        panelBIOSKOP.add(bioskopKEMBALIAN, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 250, -1, -1));

        jLabel43.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel43.setText("KEMBALIAN");
        panelBIOSKOP.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 250, -1, -1));

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton8.setText("CETAK RESI");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        panelBIOSKOP.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(311, 282, -1, -1));

        jButton9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jButton9.setText("NEXT");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        panelBIOSKOP.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(432, 282, -1, -1));

        bioskopRESI.setEditable(false);
        bioskopRESI.setColumns(20);
        bioskopRESI.setRows(5);
        jScrollPane4.setViewportView(bioskopRESI);

        panelBIOSKOP.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 157, 271, 212));

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/taul/cinema.png"))); // NOI18N
        jLabel47.setText("jLabel47");
        panelBIOSKOP.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, -1, -1));

        panelUTAMA.add(panelBIOSKOP, "card7");

        getContentPane().add(panelUTAMA, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 570, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (namaMasuk.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "WAJIB DIISI");
        }
        else{
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelPilih);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        namaPEMESAN.setText(namaMasuk.getText());
        tombolKERETA.isEnabled();
        tombolKAPAL.isEnabled();
        tombolPESAWAT.isEnabled();
        tombolBIOSKOP.isEnabled();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tombolKERETAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKERETAMouseClicked
        // TODO add your handling code here:
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelKereta);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        keretaNAMA.setText(namaMasuk.getText());
    }//GEN-LAST:event_tombolKERETAMouseClicked

    private void pilihKeretaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKeretaActionPerformed
        // TODO add your handling code here:
        if (pilihKereta.getSelectedItem().equals("PILIH JURUSAN")){
            keretaHarga.setText("");
        }
        else if(pilihKereta.getSelectedItem().equals("KUBU RAYA")){
            vip=100000;
            ekonomi=50000;
        }
        else if (pilihKereta.getSelectedItem().equals("SAMBAS")) {
            vip=200000;
            ekonomi=80000;
        }
        else if (pilihKereta.getSelectedItem().equals("KAPUAS HULU")) {
            vip=400000;
            ekonomi=280000;
        }
        else if (pilihKereta.getSelectedItem().equals("SINGKAWANG")) {
            vip=300000;
            ekonomi=160000;
        }
        
    }//GEN-LAST:event_pilihKeretaActionPerformed

    private void keretaEKONOMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaEKONOMIActionPerformed
        // TODO add your handling code here:
        if(keretaEKONOMI.isSelected()){
            keretaHarga.setText(String.valueOf(ekonomi));
        }        /* Set the Nimbus look and feel */

    }//GEN-LAST:event_keretaEKONOMIActionPerformed

    private void keretaVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keretaVIPActionPerformed
        // TODO add your handling code here:
        if (keretaVIP.isSelected()) {
            keretaHarga.setText(String.valueOf(vip));
        }
    }//GEN-LAST:event_keretaVIPActionPerformed

    private void keretaJUMLAHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keretaJUMLAHKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(keretaJUMLAH.getText());
        b=Integer.valueOf(keretaHarga.getText());
        c=a*b;
        keretaTOTAL.setText(String.valueOf(c));
    }//GEN-LAST:event_keretaJUMLAHKeyReleased

    private void keretaBAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keretaBAYARKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(keretaTOTAL.getText());
        b=Integer.valueOf(keretaBAYAR.getText());
        c=b-a;
        keretaKEMBALIAN.setText(String.valueOf(c));
    }//GEN-LAST:event_keretaBAYARKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(keretaJUMLAH.getText())>20) {
            JOptionPane.showMessageDialog(null, "JUMLAH PESANAN ANDA MEMENUHI LIMIT PEMBELIAN");
        
        }
        else{
        keretaRESI.setText(
            "TAUL TIX CORPORATION "+"\n"+"\n"+
            "NOMOR KURSI        : "+keretaNOMOR.getText()+"\n"+
            "NAMA PEMESAN       : "+keretaNAMA.getText()+"\n"+
            "JUMLAH TIKET       : "+keretaJUMLAH.getText()+"\n"+
            "TOTAL HARGA        : "+"Rp. "+keretaTOTAL.getText()+"\n"+
            "UANG YANG DIBAYAR  : "+"Rp. "+keretaBAYAR.getText()+"\n"+
            "KEMBALIAN          : "+"Rp. "+keretaKEMBALIAN.getText()+"\n"
        );}
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            keretaRESI.print();
        } catch (PrinterException ex) {
            Logger.getLogger(tiketTaul.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void keretaJUMLAHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keretaJUMLAHKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_keretaJUMLAHKeyTyped

    private void keretaNOMORKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keretaNOMORKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_keretaNOMORKeyTyped

    private void keretaBAYARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_keretaBAYARKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_keretaBAYARKeyTyped

    private void kapalEKONOMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapalEKONOMIActionPerformed
        // TODO add your handling code here:
        if (kapalEKONOMI.isSelected()) {
            kapalHARGA.setText(String.valueOf(ekonomi));
        }
    }//GEN-LAST:event_kapalEKONOMIActionPerformed

    private void kapalVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kapalVIPActionPerformed
        // TODO add your handling code here:
        if (kapalVIP.isSelected()) {
            kapalHARGA.setText(String.valueOf(vip));
        }
    }//GEN-LAST:event_kapalVIPActionPerformed

    private void pilihKAPALActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihKAPALActionPerformed
        // TODO add your handling code here:
        if (pilihKAPAL.getSelectedItem().equals("PILIH JURUSAN")){
            kapalHARGA.setText("");
        }
        else if(pilihKAPAL.getSelectedItem().equals("TANJUNG PERIOK")){
            vip=1000000;
            ekonomi=500000;
        }
        else if (pilihKAPAL.getSelectedItem().equals("TANJUNG PINANG")) {
            vip=400000;
            ekonomi=270000;
        }
        else if (pilihKAPAL.getSelectedItem().equals("SEMARANG")) {
            vip=550000;
            ekonomi=330000;
        }
        else if (pilihKAPAL.getSelectedItem().equals("SURABAYA")) {
            vip=700000;
            ekonomi=560000;
        }
        
    }//GEN-LAST:event_pilihKAPALActionPerformed

    private void kapalNOMORKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapalNOMORKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_kapalNOMORKeyTyped

    private void kapalJUMLAHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapalJUMLAHKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(kapalJUMLAH.getText());
        b=Integer.valueOf(kapalHARGA.getText());
        c=a*b;
        kapalTOTAL.setText(String.valueOf(c));
    }//GEN-LAST:event_kapalJUMLAHKeyReleased

    private void kapalJUMLAHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapalJUMLAHKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_kapalJUMLAHKeyTyped

    private void kapalBAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapalBAYARKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(kapalTOTAL.getText());
        b=Integer.valueOf(kapalBAYAR.getText());
        c=b-a;
        kapalKEMBALIAN.setText(String.valueOf(c));
    }//GEN-LAST:event_kapalBAYARKeyReleased

    private void kapalBAYARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_kapalBAYARKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_kapalBAYARKeyTyped

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(keretaJUMLAH.getText())>20) {
            JOptionPane.showMessageDialog(null, "JUMLAH PESANAN ANDA MEMENUHI LIMIT PEMBELIAN");
        
        }
        else{
        kapalRESI.setText(
            "TAUL TIX CORPORATION "+"\n"+"\n"+
            "NOMOR KURSI        : "+kapalNOMOR.getText()+"\n"+
            "NAMA PEMESAN       : "+kapalNAMA.getText()+"\n"+
            "JUMLAH TIKET       : "+kapalJUMLAH.getText()+"\n"+
            "TOTAL HARGA        : "+"Rp. "+kapalTOTAL.getText()+"\n"+
            "UANG YANG DIBAYAR  : "+"Rp. "+kapalBAYAR.getText()+"\n"+
            "KEMBALIAN          : "+"Rp. "+kapalKEMBALIAN.getText()+"\n"
        );}
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            kapalRESI.print();
        } catch (PrinterException ex) {
            Logger.getLogger(tiketTaul.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void pilihPesawatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihPesawatActionPerformed
        // TODO add your handling code here:
        if (pilihPesawat.getSelectedItem().equals("PILIH JURUSAN")){
            kapalHARGA.setText("");
        }
        else if(pilihPesawat.getSelectedItem().equals("JAKARTA")){
            vip=3000000;
            ekonomi=1500000;
        }
        else if (pilihPesawat.getSelectedItem().equals("BANDUNG")) {
            vip=4000000;
            ekonomi=275000;
        }
        else if (pilihPesawat.getSelectedItem().equals("MEDAN")) {
            vip=5500000;
            ekonomi=310000;
        }
        else if (pilihPesawat.getSelectedItem().equals("BALIKPAPAN")) {
            vip=7000000;
            ekonomi=5600000;
        }
        
    }//GEN-LAST:event_pilihPesawatActionPerformed

    private void pesawatEKONOMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesawatEKONOMIActionPerformed
        // TODO add your handling code here:
        if (pesawatEKONOMI.isSelected()) {
            pesawatHARGA.setText(String.valueOf(ekonomi));
        }
    }//GEN-LAST:event_pesawatEKONOMIActionPerformed

    private void pesawatVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesawatVIPActionPerformed
        // TODO add your handling code here:
        if (pesawatVIP.isSelected()) {
            pesawatHARGA.setText(String.valueOf(vip));
        }
    }//GEN-LAST:event_pesawatVIPActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(pesawatJUMLAH.getText())>20) {
            JOptionPane.showMessageDialog(null, "JUMLAH PESANAN ANDA MEMENUHI LIMIT PEMBELIAN");
        
        }
        else{
        pesawatRESI.setText(
            "TAUL TIX CORPORATION "+"\n"+"\n"+
            "NOMOR KURSI        : "+pesawatNOMOR.getText()+"\n"+
            "NAMA PEMESAN       : "+pesawatNAMA.getText()+"\n"+
            "JUMLAH TIKET       : "+pesawatJUMLAH.getText()+"\n"+
            "TOTAL HARGA        : "+"Rp. "+pesawatTOTAL.getText()+"\n"+
            "UANG YANG DIBAYAR  : "+"Rp. "+pesawatBAYAR.getText()+"\n"+
            "KEMBALIAN          : "+"Rp. "+pesawatKEMBALIAN.getText()+"\n"
        );}
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void pesawatBAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesawatBAYARKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(pesawatTOTAL.getText());
        b=Integer.valueOf(pesawatBAYAR.getText());
        c=b-a;
        pesawatKEMBALIAN.setText(String.valueOf(c));
    }//GEN-LAST:event_pesawatBAYARKeyReleased

    private void pesawatBAYARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesawatBAYARKeyTyped
        // TODO add your handling code here
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pesawatBAYARKeyTyped

    private void pesawatJUMLAHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesawatJUMLAHKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(pesawatJUMLAH.getText());
        b=Integer.valueOf(pesawatHARGA.getText());
        c=a*b;
        pesawatTOTAL.setText(String.valueOf(c));
    }//GEN-LAST:event_pesawatJUMLAHKeyReleased

    private void pesawatJUMLAHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesawatJUMLAHKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pesawatJUMLAHKeyTyped

    private void pesawatNOMORKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pesawatNOMORKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_pesawatNOMORKeyTyped

    private void pilihBioskopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihBioskopActionPerformed
        // TODO add your handling code here:
        if (pilihBioskop.getSelectedItem().equals("PILIH JURUSAN")){
            bioskopHARGA.setText("");
        }
        else if(pilihBioskop.getSelectedItem().equals("ANT-MAN")){
            vip=100000;
            ekonomi=50000;
        }
        else if (pilihBioskop.getSelectedItem().equals("IRON MAN")) {
            vip=150000;
            ekonomi=50000;
        }
        else if (pilihBioskop.getSelectedItem().equals("BATMAN")) {
            vip=100000;
            ekonomi=30000;
        }
        else if (pilihBioskop.getSelectedItem().equals("SUPERMAN")) {
            vip=70000;
            ekonomi=50000;
        }
    }//GEN-LAST:event_pilihBioskopActionPerformed

    private void bioskopEKONOMIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskopEKONOMIActionPerformed
        // TODO add your handling code here:
        if (bioskopEKONOMI.isSelected()) {
            bioskopHARGA.setText(String.valueOf(ekonomi));
        }
    }//GEN-LAST:event_bioskopEKONOMIActionPerformed

    private void bioskopVIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bioskopVIPActionPerformed
        // TODO add your handling code here:
        if (bioskopVIP.isSelected()) {
            bioskopHARGA.setText(String.valueOf(vip));
        }
    }//GEN-LAST:event_bioskopVIPActionPerformed

    private void bioskopNOMORKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioskopNOMORKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_bioskopNOMORKeyTyped

    private void bioskopJUMLAHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioskopJUMLAHKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(bioskopJUMLAH.getText());
        b=Integer.valueOf(bioskopHARGA.getText());
        c=a*b;
        bioskopTOTAL.setText(String.valueOf(c));
    }//GEN-LAST:event_bioskopJUMLAHKeyReleased

    private void bioskopJUMLAHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioskopJUMLAHKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_bioskopJUMLAHKeyTyped

    private void bioskopBAYARKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioskopBAYARKeyReleased
        // TODO add your handling code here:
        int a,b,c;
        a=Integer.valueOf(bioskopTOTAL.getText());
        b=Integer.valueOf(bioskopBAYAR.getText());
        c=b-a;
        bioskopKEMBALIAN.setText(String.valueOf(c));
    }//GEN-LAST:event_bioskopBAYARKeyReleased

    private void bioskopBAYARKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bioskopBAYARKeyTyped
        // TODO add your handling code here:
        if (Character.isAlphabetic(evt.getKeyChar())) {
            evt.consume();
        }
    }//GEN-LAST:event_bioskopBAYARKeyTyped

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        if (Integer.valueOf(bioskopJUMLAH.getText())>20) {
            JOptionPane.showMessageDialog(null, "JUMLAH PESANAN ANDA MEMENUHI LIMIT PEMBELIAN");
        
        }
        else{
        bioskopRESI.setText(
            "TAUL TIX CORPORATION "+"\n"+"\n"+
            "NOMOR KURSI        : "+bioskopNOMOR.getText()+"\n"+
            "NAMA PEMESAN       : "+bioskopNAMA.getText()+"\n"+
            "JUMLAH TIKET       : "+bioskopJUMLAH.getText()+"\n"+
            "TOTAL HARGA        : "+"Rp. "+bioskopTOTAL.getText()+"\n"+
            "UANG YANG DIBAYAR  : "+"Rp. "+bioskopBAYAR.getText()+"\n"+
            "KEMBALIAN          : "+"Rp. "+bioskopKEMBALIAN.getText()+"\n"
        );}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            // TODO add your handling code here:
            bioskopRESI.print();
        } catch (PrinterException ex) {
            Logger.getLogger(tiketTaul.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void tombolKAPALMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolKAPALMouseClicked
        // TODO add your handling code here:
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelKapal);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        kapalNAMA.setText(namaMasuk.getText());
    }//GEN-LAST:event_tombolKAPALMouseClicked

    private void tombolPESAWATMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolPESAWATMouseClicked
        // TODO add your handling code here:
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelPesawat);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        pesawatNAMA.setText(namaMasuk.getText());
    }//GEN-LAST:event_tombolPESAWATMouseClicked

    private void tombolBIOSKOPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tombolBIOSKOPMouseClicked
        // TODO add your handling code here:
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelBIOSKOP);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        bioskopNAMA.setText(namaMasuk.getText());
    }//GEN-LAST:event_tombolBIOSKOPMouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        panelUTAMA.removeAll();
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
        
        panelUTAMA.add(panelPilih);
        panelUTAMA.repaint();
        panelUTAMA.revalidate();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel51MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel51MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel51MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tiketTaul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tiketTaul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tiketTaul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tiketTaul.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tiketTaul().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bioskopBAYAR;
    private javax.swing.JRadioButton bioskopEKONOMI;
    private javax.swing.JLabel bioskopHARGA;
    private javax.swing.JTextField bioskopJUMLAH;
    private javax.swing.JLabel bioskopKEMBALIAN;
    private javax.swing.JLabel bioskopNAMA;
    private javax.swing.JTextField bioskopNOMOR;
    private javax.swing.JTextArea bioskopRESI;
    private javax.swing.JLabel bioskopTOTAL;
    private javax.swing.JRadioButton bioskopVIP;
    private javax.swing.ButtonGroup grupBIOSKOP;
    private javax.swing.ButtonGroup grupKAPAL;
    private javax.swing.ButtonGroup grupPESAWAT;
    private javax.swing.ButtonGroup grupkereta;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField kapalBAYAR;
    private javax.swing.JRadioButton kapalEKONOMI;
    private javax.swing.JLabel kapalHARGA;
    private javax.swing.JTextField kapalJUMLAH;
    private javax.swing.JLabel kapalKEMBALIAN;
    private javax.swing.JLabel kapalNAMA;
    private javax.swing.JTextField kapalNOMOR;
    private javax.swing.JTextArea kapalRESI;
    private javax.swing.JLabel kapalTOTAL;
    private javax.swing.JRadioButton kapalVIP;
    private javax.swing.JTextField keretaBAYAR;
    private javax.swing.JRadioButton keretaEKONOMI;
    private javax.swing.JLabel keretaHarga;
    private javax.swing.JTextField keretaJUMLAH;
    private javax.swing.JLabel keretaKEMBALIAN;
    private javax.swing.JLabel keretaNAMA;
    private javax.swing.JTextField keretaNOMOR;
    private javax.swing.JTextArea keretaRESI;
    private javax.swing.JLabel keretaTOTAL;
    private javax.swing.JRadioButton keretaVIP;
    private javax.swing.JTextField namaMasuk;
    private javax.swing.JLabel namaPEMESAN;
    private javax.swing.JPanel panelBIOSKOP;
    private javax.swing.JPanel panelKapal;
    private javax.swing.JPanel panelKereta;
    private javax.swing.JPanel panelMasuk;
    private javax.swing.JPanel panelPesawat;
    private javax.swing.JPanel panelPilih;
    private javax.swing.JPanel panelUTAMA;
    private javax.swing.JTextField pesawatBAYAR;
    private javax.swing.JRadioButton pesawatEKONOMI;
    private javax.swing.JLabel pesawatHARGA;
    private javax.swing.JTextField pesawatJUMLAH;
    private javax.swing.JLabel pesawatKEMBALIAN;
    private javax.swing.JLabel pesawatNAMA;
    private javax.swing.JTextField pesawatNOMOR;
    private javax.swing.JTextArea pesawatRESI;
    private javax.swing.JLabel pesawatTOTAL;
    private javax.swing.JRadioButton pesawatVIP;
    private javax.swing.JComboBox<String> pilihBioskop;
    private javax.swing.JComboBox<String> pilihKAPAL;
    private javax.swing.JComboBox<String> pilihKereta;
    private javax.swing.JComboBox<String> pilihPesawat;
    private javax.swing.JLabel tombolBIOSKOP;
    private javax.swing.JLabel tombolKAPAL;
    private javax.swing.JLabel tombolKERETA;
    private javax.swing.JLabel tombolPESAWAT;
    // End of variables declaration//GEN-END:variables
}
